### ISSUE TITLE
[FEATURE] Offer docker container for kidff

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiDiff#12]
While we can run kidiff using the kibot container, having a dedicate kidiff container, which would be much smaller (hopefully) would be a nice feature.

**Comment by set-soft** [comment]
I don't think this is worth the effort. Just use *kicad_auto* images instead of *kicad_auto_full* images. They are smaller. I.e.:

```
ghcr.io/inti-cmnb/kicad_auto_test    ki7                                          655b787d31f5   3 days ago      3.29GB
ghcr.io/inti-cmnb/kicad_auto         ki7                                          929efe07ed5f   2 months ago    1.48GB
ghcr.io/inti-cmnb/kicad_debian       ki7                                          553719131d32   3 days ago      1.47GB
```

Most of the size is KiCad and its dependencies. If I had to keep the same base (*kicad_debian*) you'll get nothing, using a different base means you have to download the whole image, instead of a few layers, and I have to waste GitHub storage and time to maintain the alternative base.

I'm really happy with the resources GitHub allocate to my projects, and I don't want to abuse. This is why I don't keep every single docker image that my CI/CD generates, a garbage collector discards most of them. And the images are fine tuned in a way that only the top layers changes often.

**Comment by oliv3r** [comment]
Not worth the effort is fair, but you could see if you can put that in the readme, or push the docker image here under the name kidiff :) a hack/cheat sure, but not a bad one :)
